### ISSUE TITLE
Ability to kill individual connections / reject connection toggle.

### ISSUE THREAD

**Issue by tolbertam** [scassandra/scassandra-server#100]
This is a bit of an advanced / perhaps not useful feature for everyone, but the ability to kill individual connections through the http API would help test scenarios where certain connections are torn down.

For example, the java driver maintains a separate 'control connection' that listens for schema migrations and node status events (up/down/add/remove/move/etc.).  It would be nice to be able to ensure that if the control connection socket is torn down that the driver schedules a reconnect and accommodates for any cluster state changes it may have missed.

Another interesting function would be some kind of API toggle that causes a Scassandra instance to reject new connections or start accepting them to ensure a driver continues to function with its existing connections.

**Comment by chbatey** [comment]
I like this idea. The reason I use wiremock to test HTTP integrations is that I don't trust HTTP clients, so I shouldn't trust DB drivers either :)

**Comment by tolbertam** [comment]
Thanks :).  I'd like to look into this as I need it to test a driver feature :)
