### ISSUE TITLE
Ability to specify number of alive replicas in UnavailableConfig

### ISSUE THREAD

**Issue by tolbertam** [scassandra/scassandra-server#120]
It would be useful if one could specify the number of alive replicas in UnavailableConfig.  I'll open a working PR for this shortly.

**Comment by chbatey** [comment]
I thought I did this when doing read and write timeout extra config, I could be cracking up!

**Comment by chbatey** [comment]
Is this different from alive?

**Comment by tolbertam** [comment]
Actually hrmm, you are right, you did do this!  Not sure why I had the impression that you didn't, please ignore this :)
