### ISSUE TITLE
reference.conf should never override settings from Akka

### ISSUE THREAD

**Issue by johanandren** [scassandra/scassandra-server#145]
In your `reference.conf` you are including the entire `reference.conf` from Akka 2.3.9, this is incorrect and is not how `reference.conf` files are meant to be used, it will lead to race conditions with configuration loading if users of your library are pulling in never versions of Akka.

The `reference.conf` should _only_ contain scassandra settings and not touch any Akka settings as it may load before the Akka `reference.conf`. If you want to override Akka settings that should be done in an `application.conf` file, or by providing your own chain of configuration loading using the Typesafe Config library APIs and then passing that `Configuration` to your actor system upon creation.

**Comment by chbatey** [comment]
Agreed, I think it is there from when I created the fat shaded jar that pulls in many akka jars and there reference.confs override each other then break the final jar. Happy to accept a PR.
