### ISSUE TITLE
How do I prime a map with (?)

### ISSUE THREAD

**Issue by liront2** [scassandra/scassandra-server#180]
Hi

The problem is as follows, I got this prime:

"when": {
                    "query": "UPDATE accounts SET name=?, account_address=?, account_data=?, configurations=?, last_update=?  where id=? "
                },
                "then": {
                    "variable_types":[
                        "varchar",
                        "map<text, text>",
                        "map<text, text>",
                        "map<text, text>",
                        "timestamp",
                        "uuid"
                    ],
                    "rows": [
                        {
                            "name": "QQQ",
                            "merchant_address": {
                                "name": "QQQ",
                                "address_line_1": "Johnson 19",
                                "city": "Paris",
                                "country": "FR",
                                "zip_code": "1123"
                            },
                            "merchant_data": {'contact person': 'Mark G 866-2444523232'},
                            "configurations": {'type': 'Partner', 'report': 'regular'},
                            "last_update": 4836862868426
                        }
                    ],
                    "column_types": {
                        "id": "uuid",
                        "account_address": "map<text, text>",
                        "account_data": "map<text, text>",
                        "configurations": "map<text, text>",
                        "creation_date": "timestamp",
                        "last_update": "timestamp"
                    },
                    "result": "success"

When I try to execute the UPDATE through Cassandra-Driver I get:
"Not a valid text value, expected String obtained: {
                            "name": "QQQ",
                            "merchant_address": {
                                "name": "QQQ",
                                "address_line_1": "Johnson 19",
                                "city": "Paris",
                                "country": "FR",
                                "zip_code": "1123"
                            }"
Problem is that the Driver expects a String while we have a map<text,text> in the Prime.
I'm sure it isn't the driver fault (will explain if needed), and I need to know how to make it recognise it's a map. 

Can you please assist?

**Comment by tolbertam** [comment]
Are you sure your prime is valid json?  There were a number of issues with it.

0. Some elements used single quotes instead of double quotes, this is not valid json.
1. last_update's value is too large to be a json number so needs to be quoted
2. There are missing brackets at beginning and end of the payload (I assume those were just not provided).
3. You name columns `merchant_address` and `merchant_data` in the rows data, I think this should be `account_address` and `account_data` to match the column definitions you have

I posted the following to http://localhost:8043/prime-prepared-single

```json
{
  "when": {
    "query": "UPDATE accounts SET name=?, account_address=?, account_data=?, configurations=?, last_update=? where id=? "
  },
  "then": {
    "variable_types": [
      "varchar",
      "map<text, text>",
      "map<text, text>",
      "map<text, text>",
      "timestamp",
      "uuid"
    ],
    "rows": [
      {
        "name": "QQQ",
        "account_address": {
          "name": "QQQ",
          "address_line_1": "Johnson 19",
          "city": "Paris",
          "country": "FR",
          "zip_code": "1123"
        },
        "account_data": {
          "contact person": "Mark G 866-2444523232"
        },
        "configurations": {
          "type": "Partner",
          "report": "regular"
        },
        "last_update": "4836862868426"
      }
    ],
    "column_types": {
      "id": "uuid",
      "account_address": "map<text, text>",
      "account_data": "map<text, text>",
      "configurations": "map<text, text>",
      "creation_date": "timestamp",
      "last_update": "timestamp"
    },
    "result": "success"
  }
}
```

The other thing which might not be right is that you are priming rows response from an UPDATE query.  While technically this would work with Scassandra, I wouldn't expect Cassandra to behave in this way, in any case, it should still work with any driver client.

The following driver code demonstrates this working:

```java
import com.datastax.driver.core.*;
import com.google.common.collect.ImmutableMap;

import java.util.Date;
import java.util.UUID;

public class AccountsEx {

    public static void main(String args[]) {
        Cluster cluster = Cluster.builder().addContactPoint("127.0.0.1").withPort(8042).build();
        try {
            Session session = cluster.connect();
            // Note the whitespace at the end of the statement, this is needed to match the input query exactly.
            PreparedStatement prepared = session.prepare("UPDATE accounts SET name=?, account_address=?, account_data=?, configurations=?, last_update=? where id=? ");
            // The bound values don't actually matter since we're just interested in the row contents, but they need to match the expected metadata.
            BoundStatement s = prepared.bind("test", ImmutableMap.of("test", "test"), ImmutableMap.of("test", "test"), ImmutableMap.of("test", "test"), new Date(System.currentTimeMillis()), UUID.randomUUID());
            Row r = session.execute(s).one();
            System.out.println(r);
        } finally {
            cluster.close();
        }
    }
}
```

This prints the primed row data:

> Row[QQQ, {contact person=Mark G 866-2444523232}, NULL, Sun Apr 11 00:01:08 CDT 2123, NULL, {type=Partner, report=regular}, {zip_code=1123, city=Paris, name=QQQ, country=FR, address_line_1=Johnson 19}]

**Comment by liront2** [comment]
Will try.

Another question, I'm trying to fail an UPDATE like this:
{
            "when": {
                "query": "UPDATE accounts SET name=?, merchant_address=?, merchant_data=?, configurations=?, last_update=?  where id=? "
            },
            "then": {
                "result": "write_request_timeout"
            }

Won't work when I query scassandra.
Any ideas why?

**Comment by tolbertam** [comment]
It works for me.   It might depend how you are querying it based on how you've primed it.

```java
import com.datastax.driver.core.*;

public class AccountsEx {

    public static void main(String args[]) {
        Cluster cluster = Cluster.builder().addContactPoint("127.0.0.1").withPort(8042).build();
        try {
            Session session = cluster.connect();
            PreparedStatement prepared = session.prepare("UPDATE accounts SET name=?, merchant_address=?, merchant_data=?, configurations=?, last_update=? where id=? ");
            // The bound values don't actually matter since we're just interested in the row contents, but they need to match the expected metadata.
            BoundStatement s = prepared.bind("a", "b", "c", "d", "e", "f");
            Row r = session.execute(s).one();
        } finally {
            cluster.close();
        }
    }
}
```

yields a `WriteTimeoutException` as requested:

```
Exception in thread "main" com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)
	at com.datastax.driver.core.exceptions.WriteTimeoutException.copy(WriteTimeoutException.java:73)
	at com.datastax.driver.core.exceptions.WriteTimeoutException.copy(WriteTimeoutException.java:26)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
	at AccountsEx.main(AccountsEx.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)
	at com.datastax.driver.core.exceptions.WriteTimeoutException.copy(WriteTimeoutException.java:100)
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:122)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:504)
...
```

**Comment by tolbertam** [comment]
Closing as I think the question is answered, but feel free to reopen if you would like more info :) 👍
