### ISSUE TITLE
Batch execution matcher only check 1st query.

### ISSUE THREAD

**Issue by doxtop** [scassandra/scassandra-server#194]
Batch execution matcher only check 1st query.
Looks like  variable`i` should be utilized here:

https://github.com/scassandra/scassandra-server/blob/bc2397159e6d5053723dc039b7b70c058e508a28/java-client/src/main/java/org/scassandra/matchers/BatchExecutionMatcher.java#L62
https://github.com/scassandra/scassandra-server/blob/bc2397159e6d5053723dc039b7b70c058e508a28/java-client/src/main/java/org/scassandra/matchers/BatchExecutionMatcher.java#L63

**Comment by chbatey** [comment]
Looks like a bug, a PR would be awesome

**Comment by doxtop** [comment]
ok. here it is: https://github.com/scassandra/scassandra-server/pull/196

**Comment by chbatey** [comment]
Closed via #196
