### ISSUE TITLE
Astyanax integration tests

### ISSUE THREAD

**Issue by chbatey** [scassandra/scassandra-server#31]

**Comment by rekhajoshm** [comment]
Does stubbed cassandra work with astyanax driver for unit tests? Can you provide a reference? Thanks!

**Comment by chbatey** [comment]
Hi @rekhajoshm are you using thrift or cql/native protocol with Astyanax? THere is no reason why it won't work with cql/native, I'll give that a go this week. However thrift won't work.

**Comment by rekhajoshm** [comment]
Thanks @chbatey for replying. is there any cassandra unit test framework/examples that work with astyanax thrift protocol? thanks!

**Comment by chbatey** [comment]
Stubbed Cassandra doesn't support thrift, it was developed after it was deprecated.

**Comment by rekhajoshm** [comment]
thanks i am doing a research on different cassandra flavors unit testing, i am not finding anything is astyanax thrift protocol, can take this offline.thanks for quick replies @chbatey !

**Comment by chbatey** [comment]
Thrift is due for removal in Cassandra so I would suggest you use Astyanax with the CQL/native protocol of the DataStax Cassandra Java driver.

**Comment by manuelkiessling** [comment]
I guess the need to support Astyanax just went away: http://techblog.netflix.com/2016/02/astyanax-retiring-old-friend.html

**Comment by chbatey** [comment]
Yep - closing this
