### ISSUE TITLE
Tech Debt: Make Actors extends ActorLogging instead of Logging

### ISSUE THREAD

**Issue by tepafoo** [scassandra/scassandra-server#34]
The main benefits are:
- ActorLogging is optimised in terms of I/O: see opening paragraph of this page http://doc.akka.io/docs/akka/snapshot/scala/logging.html
- Easier testing of log statements. Examples:
  - http://techblog.net-a-porter.com/2014/01/safer-testing-with-akka-eventfilter
  - http://doc.akka.io/docs/akka/snapshot/scala/testing.html#Expecting_Log_Messages

**Comment by chbatey** [comment]
Done as of a PR from @polyglotpiglet
