### ISSUE TITLE
Match prepared statement by bound parameters

### ISSUE THREAD

**Issue by adrianmkng** [scassandra/scassandra-server#48]
Match the prepared statement with the bound parameters rather than just the prepared statement itself.

**Comment by cretz** [comment]
This would be very helpful. Specifically, I don't think you need a full query processor and where clause matcher. I think you could just have a in the JSON something like:

```json
{
  "when": {
    "query": "select * from accounts where email = ?"
    "variables_match": [
      "foo@.*"
    ]
  },
  "then": {
    "variable_types": ["text"],
    "column_types": {
      "email": "text"
      "account_id": "uuid"
    },
    "rows": [
      {
        "email" = "foo@bar"
        "account_id" = "6b7c94a0-475f-11e5-aeef-0ff797c41eac"
      }
    ]
  }
}
```

This would just use regex on the toString'd value at first. Then just have the clause as a val in `PrimeMatch` and alter the get to check for that also. You'd need to update `QueryHandler` to parse the query BEFORE running the matcher. I might do a PR w/ this functionality if I get the time.

**Comment by chbatey** [comment]
I agree we wouldn't need to parse the whole query. Variables are sent over the wire separately to the query text so we can add a matcher like your example without too much work.

Would you want to have multiple primes for the same prepared statement but with different variables? 

A few notes on what would be requited in case you want to work on this your self @cretz 

This would require changes to the ExecuteHandler and the two implementations of the PreparedStoreLookup trait to take in the variables to match on as well. 

We'd need to make sure all primes for the same prepared statement had the same variable_types as the PrepareHandler needs that information before a prepared statement is executed.

**Comment by cretz** [comment]
I was working on this but I kept getting an error. Then I saw that https://github.com/scassandra/scassandra-server/commit/f58fb154de2a5680a43dcd4a2235a6b22f28d14b broke query parsing for parameters (and even changed the test the no longer handle parameters instead of fixing it). Is re-implementing parameter parsing on the roadmap or would I need to tackle that as well?

**Comment by tolbertam** [comment]
@cretz, just for background as to why I made that change; f58fb15 does not break parsing for query parameters.  Query flags and thus Parameters are not supported in protocol version one (C* 1.2) as they were added in v2 (C* 2.0), therefore the test was not valid.  Although I admit there isn't really an appropriate test for testing with protocol v2, so we should add one (On another note i'm working on proto v3 and v4 support in #76 which I will make sure to include this).

Query flags and parameters are still parsed for clients supporting protocol version V2 via [AbstractMessageFactory#parseQueryRequest](https://github.com/scassandra/scassandra-server/blob/27b4a2ff1c356a46614012371c15217e2af9d347/server/src/main/scala/org/scassandra/server/cqlmessages/AbstractMessageFactory.scala#L123-L138) which is called in [QueryHandler](https://github.com/scassandra/scassandra-server/blob/27b4a2ff1c356a46614012371c15217e2af9d347/server/src/main/scala/org/scassandra/server/actors/QueryHandler.scala#L55) and recorded in the activity log.

**Comment by tolbertam** [comment]
I just saw your comment regarding:

> You'd need to update QueryHandler to parse the query BEFORE running the matcher.

Since this applies to Bound Statements shouldn't QueryHandler not apply anyways?  QueryHandler is for regular (non prepared statements) and the reason why we need to match on the prime for the query is that we need the variable types in order to parse the parameters.  Although I think even with Prepared Statements in ExecuteHandler you are not going to be able to discern the type of variables without a Prime's variableTypes.  On the other hand this could apply for normal queries with parameters as well so QueryHandler could in theory apply here as well too.

I may just be misreading into your comments and maybe you are alluding to this, but I think you could come up with a way to find candidate primes matching 'query' text, and then grab the variable types from the first found Prime and then parse the parameters and find the match from 'variables_match' from the candidate primes to find which one applies.

**Comment by chbatey** [comment]
Yeah for this feature says Prepared statements but the equivalent feature for regular queries would also be useful tho PS are used a lot more than Queries with variables. 

The capturing of parameters for queries and prepared statements are tested under the integration tests tho the Query ones are hard to find as they are called QueryBuilder tests which use variables under the covers.

Checkout QueryBuilderTest and nearly all of the PreparedStatement withMatcher tests as nearly all of them match on bound variables.

**Comment by cretz** [comment]
Ok, will do. In my case I execute statements frequently without preparing them but of course still use parameters to prevent injection. It is definitely a use case I have to solve for myself. My early base integration test:

```java
package queries;

import java.util.List;

import org.junit.Test;
import org.scassandra.cql.CqlType;
import org.scassandra.cql.PrimitiveType;
import org.scassandra.http.client.PrimingRequest;

import com.google.common.collect.ImmutableMap;

import common.AbstractScassandraTest;
import common.CassandraExecutor;
import common.CassandraResult;
import common.CassandraRow;
import static org.junit.Assert.*;
import static org.scassandra.http.client.PrimingRequest.then;
import static org.scassandra.http.client.types.ColumnMetadata.*;

public class PrimingWithVariableMatchers extends AbstractScassandraTest {

    public PrimingWithVariableMatchers(CassandraExecutor cassandraExecutor) {
        super(cassandraExecutor);
    }

    @Test
    public void testSimpleStringVariablePatternFailure() {
        PrimingRequest.Then then = then().
                withVariableMatchers("C.*").
                withRows(ImmutableMap.of("name", "Chad")).
                build();
        PrimingRequest request = PrimingRequest.queryBuilder().
                withQuery("select name from people where name = ?").
                withThen(then).
                build();
        primingClient.prime(request);
        CassandraResult result = cassandra().executeQuery("select name from people where name = ?", "Chad");
        List<CassandraRow> rows = result.rows();
        assertEquals(0, rows.size());
    }
}
```

The problem is that, in `QueryHandler` that runs `msgFactory.parseQueryRequest(stream, queryBody, types)`, the `parameters` list in the result is always empty. I will dig into making the parser read parameters also.

**Comment by chbatey** [comment]
Thinking about this more for prepared statements it seems wrong to allow primes for the same text but with different variable types. So i'd like to do this with something like this

```json
{
  "when": {
    "query": "select * from people where name = ?"
  },
  "then": {
    "variable_types": [
      "varchar"
    ],
    "cases": [
      {
        "matchers": {
          "varibles": [
            "Chris"
          ]
        },
        "rows": [
          {
            "name": "Chris"
          }
        ],
        "result": "success",
        "column_types": {
          "name": "varchar"
        }
      },
      {
        "matchers": {
          "varibles": [
            "Andrew"
          ]
        },
        "result": "read_timeout"
      }
    ]
  }
}
```

As this would be a breaking change it would also need us to start using Accept/Content-type

**Comment by baddapuri9** [comment]
Further to our conversation earlier, we currently just need functionality to prime behaviour based on query parameters of type text.

**Comment by chbatey** [comment]
@baddapuri9 for the query text is that an exact match or a pattern? Will just be doing exact matches for now

**Comment by chbatey** [comment]
I have a very crude version working that'll only work if the default JSON parsing (your prime is passed over http/json to scassandra server) matches exactly how the cql message parsing works. This will rarely work as json types < cassandra types so it is a lossy conversion however it will work for text.

You can start testing on the multi-prime-for-variales branch i'll push tonight.

Feel free to review the code @baddapuri9 , at a minimum review the API for doing a prime that can have many results. So far it looks like:

```java
        MultiPrimeRequest prime = MultiPrimeRequest.request()
                .withWhen(when()
                        .withQuery(query))
                .withThen(then()
                        .withVariableTypes(TEXT)
                        .withOutcomes(
                                outcome(match().withVariableMatchers(variableMatch().withMatcher("Chris").build()), action().withResult(Result.success)),
                                outcome(match().withVariableMatchers(variableMatch().withMatcher("Andrew").build()), action().withResult(Result.read_request_timeout))
                        )
                )
                .build();
```

Feed back welcome. Will aim to release the proper functionality by the end of next week.

**Comment by tkgregory** [comment]
Thanks Chris. We were going to try it out but the tests are currently failing in the multi-prime-for-variales branch with a CodecNotFoundException. Did something get missed?

**Comment by chbatey** [comment]
Stack trace + example test case?

**Comment by tkgregory** [comment]
preparedstatements.PreparedStatementPrimeOnVariablesTest30 > testPrimeBasedOnMatcherUUIDs FAILED
    com.datastax.driver.core.exceptions.CodecNotFoundException: Codec not found for requested operation: [timeuuid <-> java.util.UUID]

[Full log](https://s3.amazonaws.com/archive.travis-ci.org/jobs/99091239/log.txt)

**Comment by chbatey** [comment]
Something with the Cassandra 3 driver, you can ignore that test and try it with 2.0/2.1

**Comment by chbatey** [comment]
hey @tkgregory @baddapuri9 pushed changes to support most types, let me know how you get on

**Comment by adamdougal** [comment]
Hey @chbatey, we've now got this working! We have one problem which would still stop us using it though. For the query we're making we are inserting a UUID that is generated by the app, therefore our tests won't know what to prime. We don't really care about what the UUID is in the tests, so is there anyway we could have an any() matcher like in mockito?

**Comment by chbatey** [comment]
Sounds like a good idea, it's why I put the match inside a "variableMatch" so we could have multiple types, will look at it tonight

**Comment by chbatey** [comment]
Got this working, I changed some names for the static methods.

Example:

```java
String query = "select * from person where name = ? and age = ?";
        Map<String, Object> rows = ImmutableMap.of(
                "name", "Chris",
                "age", 30
        );
        Map<String, CqlType> colTypes = ImmutableMap.of("age", PrimitiveType.INT, "name", PrimitiveType.TEXT);
        MultiPrimeRequest prime = MultiPrimeRequest.request()
                .withWhen(when()
                        .withQuery(query))
                .withThen(then()
                        .withVariableTypes(TEXT, INT)
                        .withOutcomes(
                                outcome(match().withVariableMatchers(exactMatch("Andrew"), anyMatch()),
                                        action().withRows(rows).withColumnTypes(colTypes)),
                                outcome(match().withVariableMatchers(anyMatch(), anyMatch()),
                                        action().withResult(Result.read_request_timeout).withColumnTypes(colTypes))
                        )
                )
                .build();

        primingClient.multiPrime(prime);
```

Still got quite a new types to support + decide what to do if none of the outcomes match, but should work for your usecase now?

**Comment by adamdougal** [comment]
Hi @chbatey,

We tested the latest version of the branch and it works just as we expected. We can prime queries with a mixture of exact matches and any matches.

Thanks

**Comment by adamdougal** [comment]
This is done now right? Could be closed.

**Comment by chbatey** [comment]
Yes!
