### ISSUE TITLE
How do I provide  a cassandra yaml to  override the default configuration?

### ISSUE THREAD

**Issue by KodeSeeker** [scassandra/scassandra-server#64]
Im trying to provide a cassandra yaml to simulate testing testing with different configuration parameters for Cassandra .Does the library support this? If yes, how do I go about it?

**Comment by chbatey** [comment]
Hi @KodeSeeker stubbed Cassandra doesn't embed a real cassandra so it doesn't make sense to give it a cassandra.yaml 

What are you trying to test, we can add support to make anything appear as if the server is configured different ways.

**Comment by chbatey** [comment]
Closing, please raise a feature request for specific functionality (you may already have it was SSL).
