### ISSUE TITLE
INT, TIMESTAMP types aren't working

### ISSUE THREAD

**Issue by williamconti** [scassandra/scassandra-server#74]
I am having an issue in scassandra about my variable types, here are all the files involved in the issue.

//////// AladinClusterMock.java ///////

            public class AladinClusterMock {	
            private PrimingClient primingClient;
            private ActivityClient activityClient;
            private Scassandra scassandra;
            private EvtAladinDao aladindao;
            private EvtAladin value2;
            private ArrayList<EvtAladin> evts = new ArrayList<EvtAladin>();
            private Session session;
            private Cluster cluster;
            private String query;
            @BeforeClass
            public void startScassandraServer() throws Exception {

        		scassandra = ScassandraFactory.createServer(9042,9260);
        		scassandra.start();
        		primingClient = scassandra.primingClient();
        		activityClient = scassandra.activityClient();
        		
        		Builder builder = Cluster.builder();
        		cluster = builder.addContactPoint("127.0.0.1").build();
        		session = cluster.connect();
        		
        		query = "INSERT INTO aladin.aladin_evt ("
        				+ "code_agence,"
        				+ "code_evt,"
        				+ "bucket,"
        				+ "date_evt,"
        				+ "no_lt,"
        				+ "precocite,"
        				+ " VALUES (?,?,?,?,?)";
        		
        		value2 = new EvtAladin().setCode_agence("ALFORTVILLE")
        				.setCode_evt("Distri")
        				.setBucket(1)
        				.setDate_evt(new Timestamp(0))
        				.setNo_lt("EE9887230GB")
        		evts.add(value2);		
            }

            @Test
            public void testInsertEvt(){
                PrimingRequest preparedStatementPrime = PrimingRequest.preparedStatementBuilder()
                        .withQuery(query)
                        .withVariableTypes(VARCHAR, VARCHAR, INT, TIMESTAMP, VARCHAR)
                        .build();
                primingClient.prime(preparedStatementPrime);

                AladinMicroserviceApplication.cassandraSession = session;
                aladindao = EvtAladinDao.getInstance();
                aladindao.insertEvts(evts);

                PreparedStatementExecution expectedPreparedStatement = PreparedStatementExecution.builder()
                        .withPreparedStatementText(query)
                        .withConsistency("ONE")
                        .withVariables("ALFORTVILLE","Distri",1,new Timestamp(0),"EE9887230GB")
                        .build();
                assertTrue(activityClient.retrievePreparedStatementExecutions() == preparedStatementRecorded(expectedPreparedStatement)); 	
            }

        }

//////// AladinDao.java /////

            public class EvtAladinDao implements EvtAladinDaoInterface{
            private static Session session;
            private static EvtAladinDao INSTANCE = null;
            private PreparedStatement statementLt;
            public static final int LOT = 100;
            
            
            public static EvtAladinDao getInstance(){
                if (EvtAladinDao.INSTANCE == null){
                    EvtAladinDao.INSTANCE = new EvtAladinDao();
                }
                return EvtAladinDao.INSTANCE;
            }
            
            private EvtAladinDao() {
                if(session==null){
                    session = AladinMicroserviceApplication.cassandraSession;
                
                    String insertQuery ="INSERT INTO aladin.aladin_evt ("
                            + "code_agence,"
                            + "code_evt,"
                            + "bucket,"
                            + "date_evt,"
                            + "no_lt)"
                            + " VALUES (?,?,?,?,?)";
                    statementLt = session.prepare(insertQuery);
                }
            }
            public boolean insertEvts(List<EvtAladin> evts){
				BoundStatement boundStatement = new BoundStatement(statementLt);
				int nbEvtTraites=0;
				ArrayList<ResultSetFuture> futures = new ArrayList<ResultSetFuture>();
				for(EvtAladin evt:evts){
						
						ResultSetFuture res =
	                       session.executeAsync(boundStatement.bind(
 								evt.getCode_agence(),
								evt.getCode_evt(),
								evt.getBucket(),
								evt.getDate_evt(),
								evt.getNo_lt()))
						futures.add(res);			
									
				}
				
		return true;
	}
}

So, when i run the test it gives me an error:

com.datastax.driver.core.exceptions.InvalidTypeException: Invalid type for value 2 of CQL type varchar, expecting class java.lang.String but class java.lang.Integer provided

The "bucket" field is an int, it seems that scassandra is expecting a String and not an integer.

Also this error points to the method insertEvt, wich is odd because it works perfectly on another test where scassandra isn't involved.

Am I missing something? I edited my code to make it more understandable, my apologise if something isn't clear.

**Comment by chbatey** [comment]
Hi @williamconti the most likely cause is your prime is happening after the prepare. For prepared statements they need to happen beforehand as that is when C* tells the driver what types your variables are. 

The easiest way to verify is looking for the log "Storing prime for prepared statement" and you can see if that does happen beforehand.

**Comment by chbatey** [comment]
Btw if it doesn't find a prime it always defaults variables to varchar, hence the error message

**Comment by williamconti** [comment]
Somehow after a few changes my code works, but I still have some problems with my test:

If i change my query from: 
"INSERT INTO aladin.aladin_evt ....."

To:
"INSERT INTO aladin_evt ....."

It still gives me the same error but when I continue with the working query and when I compare them, I have some problems with my values, here are the values returned:

activityClient.retrievePreparedStatementExecutions():
".....   variables=[ALFORTVILLE, Distri, 1.0, 0.0, EE9887230GB ..... " 

preparedStatementRecorded(expectedPreparedStatement):
 "...... variables=[ALFORTVILLE, Distri, 1, 1970-01-01 01:00:00.0, EE9887230GB, ....."

Strings are ok, but int and timestamps are not what i expect...

**Comment by chbatey** [comment]
Regarding changing the query, you can prime using a regex which means it won't matter e.g INSERT INTO .*aladin_evt

Beware you'll need to escape any regex characters that appear in your query.

@williamconti what did you pass in as your int and timestamp to get these values? As the values are serialised as JSON to go back to the client some type information is lost, if you use the hamcrest matcher it converts it back for you as the server also sends the CQL types back.

**Comment by williamconti** [comment]
I am simply sending a "new Timestamp(0)" and some random numbers to a DAO. In a way my test follows the same pattern that you gave into your example, only the values are chaning.

**Comment by chbatey** [comment]
A new Timestamp(0) where 0 is the spoch is the date 1970-01-01 01:00:00.0 assuming the timezone GMT. What are you expecting?

**Comment by williamconti** [comment]
Well as I said earlier, I am expecting:

1970-01-01 01:00:00.0 in my timestamp field
1 in my Interger field.

But i get 0.0 and 1.0, wich is odd.

**Comment by chbatey** [comment]
They are serialised as Jain between the client and the server. All numbers are doubles hence 1.0, all time stamps are longs. 

The hamcrest matcher does the conversion back as the type information is also sent back. With it u can match against a date and an int as you'd expect.
