### ISSUE TITLE
Record 'Prepare' executions in ActivityLog

### ISSUE THREAD

**Issue by tolbertam** [scassandra/scassandra-server#77]
In the java driver we're doing a bit of work around optimizing when the driver sends 'prepare' messages to C* nodes to prepare statements on them (see [JAVA-801](https://datastax-oss.atlassian.net/browse/JAVA-801)).  It would be super useful if Scassandra recorded whenever a 'prepare' message was received in PrepareHandler in ActivityLog so it can be exposed through ActivityClient.  Does this sound like a good idea?  We can work on this and open up a PR when it's ready.

**Comment by chbatey** [comment]
Duplicate of #23 I believe

**Comment by tolbertam** [comment]
Yep, this is definitely a duplicate!  Closing this one and we'll track under #23.
