### ISSUE TITLE
Support more error results in PrimingRequest

### ISSUE THREAD

**Issue by tolbertam** [scassandra/scassandra-server#92]
Today a PrimingRequest can be configured to return 'success', 'read_request_timeout', and 'write_request_timeout'.  It would be useful if we could return more errors that are especially difficult to reproduce with a real cassandra instance.  We could cover most of the error codes in the [v2 spec under section 8](https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v2.spec#L840).

**Comment by chbatey** [comment]
+1

**Comment by tolbertam** [comment]
Was merged in. Closing.
